### ISSUE TITLE
Random Event Backend

### ISSUE THREAD

**Issue by CTOverton** [CTOverton/like-birbs#13]
Yeah

**Comment by SageTheWizard** [comment]
added random event back end 
TODO for Front end
Need: 2 Dialog Fragments
   - 1 Just has a confirm button ("Okay I know this event happened")
   - 1 Has a Yes / No button 
            - ("Yes I want to open crashed Ship, No I want to ignore it")

When the randomEvent() gets called, it will return an integer which can be compared against the public static final ints in Enviorment ... 
Access with "Enviorment.<EVENT_CODE_NAME_HERE>" to determine the fragment.
if the Event is Enviorment.CRASHED_SHIP_EVENT (10) is returned from the function, call the 2nd type of dialog fragment. 
if Event is Enviorment.NO_EVENT (0) do nothing
if Event is anything else, compare it against the static ints to get the text (I might add a string array in the strings.xml resource file)
